#!/usr/bin/env bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEMS_DIR="$CONFIG_DIR/items"

source "$PLUGIN_DIR/colors.sh"

# Bar style
bar=(
    position=top
    height=33
    blur_radius=32
    sticky=on
    margin=0
    color="$BAR_COLOR"
)
sketchybar --bar "${bar[@]}"

default=(
    background.color="$ITEM_BG_COLOR"
    background.corner_radius=5
    background.height=30
    background.padding_left=0
    background.padding_right=0
    padding_left=0
    padding_right=0
    y_offset=1
    icon.font="Hack Nerd Font:Regular:12.0"
    label.font="CommitMono:Regular:15.0"
    icon.color="$FG_COLOR"
    label.color="$FG_COLOR"
    # icon.padding_left=10
    # icon.padding_right=0
    # label.padding_left=10
    # label.padding_right=10
    icon.y_offset=0
    label.y_offset=0
)
sketchybar --default "${default[@]}"


# Left side
source "$ITEMS_DIR/aerospace.sh"
source "$ITEMS_DIR/front_app.sh"

# Right side
source "$ITEMS_DIR/clock.sh"
source "$ITEMS_DIR/calendar.sh"
source "$ITEMS_DIR/battery.sh"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
